export const airmen = [
  {
    email: 'admin@mail.com',
    password: '244466666',
    rank: 'GS-12',
    firstName: 'Anon',
    middleName: 'None',
    lastName: 'Ymous',
    organization: '123 ADMN',
    officeSymbol: 'ADMN',
    dodId: '1234567890',
  },
  {
    email: 'janell.nieves@us.af.mil',
    password: '55555',
    rank: 'Maj',
    firstName: 'Janell',
    middleName: 'Luna',
    lastName: 'Nieves',
    organization: '23 ABW',
    officeSymbol: 'D1B',
    dodId: '8245801312',
  },
  {
    email: 'gill.lynch@us.af.mil',
    password: '55555',
    rank: 'Cpt',
    firstName: 'Gill',
    middleName: 'Frank',
    lastName: 'Lynch',
    organization: '93 AGOW',
    officeSymbol: 'E4G',
    dodId: '5277021767',
  },
  {
    email: 'felicia.salazar@us.af.mil',
    password: '55555',
    rank: 'Cpt',
    firstName: 'Felicia',
    middleName: 'Ebony',
    lastName: 'Salazar',
    organization: '140 MXG',
    officeSymbol: 'D1G',
    dodId: '2503713728',
  },
  {
    email: 'gayle.pierce@us.af.mil',
    password: '55555',
    rank: 'MSgt',
    firstName: 'Gayle',
    middleName: 'Russell',
    lastName: 'Pierce',
    organization: '2 BW',
    officeSymbol: 'C6G',
    dodId: '7317352502',
  },
  {
    email: 'candice.palmer@us.af.mil',
    password: '55555',
    rank: 'LtCol',
    firstName: 'Candice',
    middleName: 'Juliana',
    lastName: 'Palmer',
    organization: '701 MUNSS',
    officeSymbol: 'B7D',
    dodId: '2637458446',
  },
  {
    email: 'kimberly.bond@us.af.mil',
    password: '55555',
    rank: 'SMSgt',
    firstName: 'Kimberly',
    middleName: 'Mcgee',
    lastName: 'Bond',
    organization: '701 MUNSS',
    officeSymbol: 'F5C',
    dodId: '3301638108',
  },
  {
    email: 'carolina.watson@us.af.mil',
    password: '55555',
    rank: 'Cpt',
    firstName: 'Carolina',
    middleName: 'Hess',
    lastName: 'Watson',
    organization: '701 MUNSS',
    officeSymbol: 'C1G',
    dodId: '8668845171',
  },
  {
    email: 'maritza.rios@us.af.mil',
    password: '55555',
    rank: 'LtCol',
    firstName: 'Maritza',
    middleName: 'Lindsey',
    lastName: 'Rios',
    organization: '93 AGOW',
    officeSymbol: 'F9C',
    dodId: '8818201655',
  },
  {
    email: 'barber.gilmore@us.af.mil',
    password: '55555',
    rank: '2Lt',
    firstName: 'Barber',
    middleName: 'Haynes',
    lastName: 'Gilmore',
    organization: '2 BW',
    officeSymbol: 'D6C',
    dodId: '7857174641',
  },
  {
    email: 'bolton.howell@us.af.mil',
    password: '55555',
    rank: '2Lt',
    firstName: 'Bolton',
    middleName: 'Dolores',
    lastName: 'Howell',
    organization: '1 FW',
    officeSymbol: 'D6F',
    dodId: '5874866075',
  },
  {
    email: 'kelsey.schneider@us.af.mil',
    password: '55555',
    rank: 'MSgt',
    firstName: 'Kelsey',
    middleName: 'Caldwell',
    lastName: 'Schneider',
    organization: '140 MXG',
    officeSymbol: 'E4E',
    dodId: '5063416548',
  },
  {
    email: 'morton.campbell@us.af.mil',
    password: '55555',
    rank: 'Maj',
    firstName: 'Morton',
    middleName: 'Hope',
    lastName: 'Campbell',
    organization: '701 MUNSS',
    officeSymbol: 'D2B',
    dodId: '1737753741',
  },
  {
    email: 'eliza.fox@us.af.mil',
    password: '55555',
    rank: 'Maj',
    firstName: 'Eliza',
    middleName: 'Leah',
    lastName: 'Fox',
    organization: '1 FW',
    officeSymbol: 'C4D',
    dodId: '2254632018',
  },
  {
    email: 'enid.whitfield@us.af.mil',
    password: '55555',
    rank: 'SMSgt',
    firstName: 'Enid',
    middleName: 'Bradley',
    lastName: 'Whitfield',
    organization: '377 SFG',
    officeSymbol: 'E8F',
    dodId: '4162881303',
  },
  {
    email: 'walker.hart@us.af.mil',
    password: '55555',
    rank: 'CMSgt',
    firstName: 'Walker',
    middleName: 'Sybil',
    lastName: 'Hart',
    organization: '1 FW',
    officeSymbol: 'B7A',
    dodId: '2081616367',
  },
  {
    email: 'michael.gutierrez@us.af.mil',
    password: '55555',
    rank: 'Col',
    firstName: 'Michael',
    middleName: 'Jenna',
    lastName: 'Gutierrez',
    organization: '140 MXG',
    officeSymbol: 'B2F',
    dodId: '1171121827',
  },
  {
    email: 'joanne.faulkner@us.af.mil',
    password: '55555',
    rank: 'Maj',
    firstName: 'Joanne',
    middleName: 'Wilkerson',
    lastName: 'Faulkner',
    organization: '377 SFG',
    officeSymbol: 'D9E',
    dodId: '8565272540',
  },
  {
    email: 'valentine.massey@us.af.mil',
    password: '55555',
    rank: 'Cpt',
    firstName: 'Valentine',
    middleName: 'Maude',
    lastName: 'Massey',
    organization: '140 MXG',
    officeSymbol: 'G9A',
    dodId: '2648012238',
  },
  {
    email: 'henrietta.odom@us.af.mil',
    password: '55555',
    rank: 'SSgt',
    firstName: 'Henrietta',
    middleName: 'Matilda',
    lastName: 'Odom',
    organization: '23 ABW',
    officeSymbol: 'C5B',
    dodId: '0475751743',
  },
  {
    email: 'rivas.moon@us.af.mil',
    password: '55555',
    rank: 'A1C',
    firstName: 'Rivas',
    middleName: 'Robbie',
    lastName: 'Moon',
    organization: '701 MUNSS',
    officeSymbol: 'B5F',
    dodId: '7762082850',
  },
  {
    email: 'benton.green@us.af.mil',
    password: '55555',
    rank: '1Lt',
    firstName: 'Benton',
    middleName: 'Mayra',
    lastName: 'Green',
    organization: '23 ABW',
    officeSymbol: 'F1C',
    dodId: '1857036614',
  },
  {
    email: 'stephanie.knox@us.af.mil',
    password: '55555',
    rank: 'TSgt',
    firstName: 'Stephanie',
    middleName: 'Althea',
    lastName: 'Knox',
    organization: '93 AGOW',
    officeSymbol: 'B3D',
    dodId: '5580508072',
  },
  {
    email: 'hicks.barnes@us.af.mil',
    password: '55555',
    rank: 'MSgt',
    firstName: 'Hicks',
    middleName: 'Robertson',
    lastName: 'Barnes',
    organization: '1 FW',
    officeSymbol: 'D8G',
    dodId: '0260573603',
  },
  {
    email: 'bass.livingston@us.af.mil',
    password: '55555',
    rank: 'A1C',
    firstName: 'Bass',
    middleName: 'Ball',
    lastName: 'Livingston',
    organization: '2 BW',
    officeSymbol: 'G9D',
    dodId: '5313311840',
  },
  {
    email: 'knox.wood@us.af.mil',
    password: '55555',
    rank: 'Maj',
    firstName: 'Knox',
    middleName: 'Kidd',
    lastName: 'Wood',
    organization: '1 FW',
    officeSymbol: 'G7C',
    dodId: '0603734156',
  },
  {
    email: 'long.hanson@us.af.mil',
    password: '55555',
    rank: 'SSgt',
    firstName: 'Long',
    middleName: 'Susanna',
    lastName: 'Hanson',
    organization: '377 SFG',
    officeSymbol: 'D6E',
    dodId: '8846453500',
  },
  {
    email: 'beulah.flores@us.af.mil',
    password: '55555',
    rank: 'Cpt',
    firstName: 'Beulah',
    middleName: 'Larsen',
    lastName: 'Flores',
    organization: '93 AGOW',
    officeSymbol: 'C3E',
    dodId: '7243618712',
  },
  {
    email: 'mathis.winters@us.af.mil',
    password: '55555',
    rank: 'Col',
    firstName: 'Mathis',
    middleName: 'Moss',
    lastName: 'Winters',
    organization: '93 AGOW',
    officeSymbol: 'D2G',
    dodId: '5031116322',
  },
  {
    email: 'freda.hendricks@us.af.mil',
    password: '55555',
    rank: 'Amn',
    firstName: 'Freda',
    middleName: 'Dora',
    lastName: 'Hendricks',
    organization: '93 AGOW',
    officeSymbol: 'C6A',
    dodId: '1453545486',
  },
  {
    email: 'whitfield.tanner@us.af.mil',
    password: '55555',
    rank: 'Maj',
    firstName: 'Whitfield',
    middleName: 'Mccarthy',
    lastName: 'Tanner',
    organization: '23 ABW',
    officeSymbol: 'A7A',
    dodId: '0112752386',
  },
  {
    email: 'randi.cunningham@us.af.mil',
    password: '55555',
    rank: 'A1C',
    firstName: 'Randi',
    middleName: 'Jeannette',
    lastName: 'Cunningham',
    organization: '140 MXG',
    officeSymbol: 'G5A',
    dodId: '8566742008',
  },
  {
    email: 'georgette.downs@us.af.mil',
    password: '55555',
    rank: 'Maj',
    firstName: 'Georgette',
    middleName: 'Ellis',
    lastName: 'Downs',
    organization: '2 BW',
    officeSymbol: 'F3F',
    dodId: '8653065108',
  },
  {
    email: 'ophelia.benton@us.af.mil',
    password: '55555',
    rank: '2Lt',
    firstName: 'Ophelia',
    middleName: 'Celia',
    lastName: 'Benton',
    organization: '1 FW',
    officeSymbol: 'E9E',
    dodId: '2756061323',
  },
  {
    email: 'cara.solis@us.af.mil',
    password: '55555',
    rank: 'TSgt',
    firstName: 'Cara',
    middleName: 'Wise',
    lastName: 'Solis',
    organization: '23 ABW',
    officeSymbol: 'F9G',
    dodId: '5700375256',
  },
  {
    email: 'lynnette.gallagher@us.af.mil',
    password: '55555',
    rank: 'SMSgt',
    firstName: 'Lynnette',
    middleName: 'Tyler',
    lastName: 'Gallagher',
    organization: '93 AGOW',
    officeSymbol: 'B8D',
    dodId: '3724100712',
  },
  {
    email: 'clarke.riggs@us.af.mil',
    password: '55555',
    rank: 'Maj',
    firstName: 'Clarke',
    middleName: 'Joyner',
    lastName: 'Riggs',
    organization: '377 SFG',
    officeSymbol: 'B4D',
    dodId: '2880271535',
  },
  {
    email: 'neva.manning@us.af.mil',
    password: '55555',
    rank: 'TSgt',
    firstName: 'Neva',
    middleName: 'Hilda',
    lastName: 'Manning',
    organization: '1 FW',
    officeSymbol: 'G6E',
    dodId: '0205316427',
  },
  {
    email: 'elizabeth.sheppard@us.af.mil',
    password: '55555',
    rank: 'Amn',
    firstName: 'Elizabeth',
    middleName: 'Annabelle',
    lastName: 'Sheppard',
    organization: '377 SFG',
    officeSymbol: 'F7C',
    dodId: '6886811701',
  },
  {
    email: 'hattie.mann@us.af.mil',
    password: '55555',
    rank: 'SMSgt',
    firstName: 'Hattie',
    middleName: 'Bridgette',
    lastName: 'Mann',
    organization: '93 AGOW',
    officeSymbol: 'G4G',
    dodId: '3273202844',
  },
  {
    email: 'jo.duffy@us.af.mil',
    password: '55555',
    rank: 'A1C',
    firstName: 'Jo',
    middleName: 'Clark',
    lastName: 'Duffy',
    organization: '2 BW',
    officeSymbol: 'G2D',
    dodId: '7866511320',
  },
  {
    email: 'whitaker.duke@us.af.mil',
    password: '55555',
    rank: 'TSgt',
    firstName: 'Whitaker',
    middleName: 'Carlene',
    lastName: 'Duke',
    organization: '1 FW',
    officeSymbol: 'A5G',
    dodId: '8723687610',
  },
  {
    email: 'rutledge.aguirre@us.af.mil',
    password: '55555',
    rank: 'SSgt',
    firstName: 'Rutledge',
    middleName: 'England',
    lastName: 'Aguirre',
    organization: '93 AGOW',
    officeSymbol: 'E6E',
    dodId: '6806086022',
  },
  {
    email: 'dale.buckley@us.af.mil',
    password: '55555',
    rank: 'SrA',
    firstName: 'Dale',
    middleName: 'Polly',
    lastName: 'Buckley',
    organization: '1 FW',
    officeSymbol: 'D8F',
    dodId: '2528778611',
  },
  {
    email: 'cooper.ross@us.af.mil',
    password: '55555',
    rank: 'Cpt',
    firstName: 'Cooper',
    middleName: 'Cathy',
    lastName: 'Ross',
    organization: '701 MUNSS',
    officeSymbol: 'A2C',
    dodId: '7542422453',
  },
  {
    email: 'porter.becker@us.af.mil',
    password: '55555',
    rank: '2Lt',
    firstName: 'Porter',
    middleName: 'Paul',
    lastName: 'Becker',
    organization: '93 AGOW',
    officeSymbol: 'D5G',
    dodId: '7406371603',
  },
  {
    email: 'kayla.schultz@us.af.mil',
    password: '55555',
    rank: 'LtCol',
    firstName: 'Kayla',
    middleName: 'Mattie',
    lastName: 'Schultz',
    organization: '701 MUNSS',
    officeSymbol: 'F2B',
    dodId: '5160402844',
  },
  {
    email: 'bush.jensen@us.af.mil',
    password: '55555',
    rank: 'Maj',
    firstName: 'Bush',
    middleName: 'Evelyn',
    lastName: 'Jensen',
    organization: '2 BW',
    officeSymbol: 'F2F',
    dodId: '7754230718',
  },
  {
    email: 'melisa.contreras@us.af.mil',
    password: '55555',
    rank: 'LtCol',
    firstName: 'Melisa',
    middleName: 'Sampson',
    lastName: 'Contreras',
    organization: '2 BW',
    officeSymbol: 'B2C',
    dodId: '2632865753',
  },
  {
    email: 'mclaughlin.rivers@us.af.mil',
    password: '55555',
    rank: 'A1C',
    firstName: 'Mclaughlin',
    middleName: 'Carr',
    lastName: 'Rivers',
    organization: '377 SFG',
    officeSymbol: 'C1D',
    dodId: '5818318103',
  },
  {
    email: 'waters.russell@us.af.mil',
    password: '55555',
    rank: 'Cpt',
    firstName: 'Waters',
    middleName: 'Ashley',
    lastName: 'Russell',
    organization: '1 FW',
    officeSymbol: 'G9C',
    dodId: '7207648607',
  },
  {
    email: 'waller.vinson@us.af.mil',
    password: '55555',
    rank: 'SMSgt',
    firstName: 'Waller',
    middleName: 'Aurelia',
    lastName: 'Vinson',
    organization: '140 MXG',
    officeSymbol: 'G4E',
    dodId: '6084328404',
  },
  {
    email: 'karla.golden@us.af.mil',
    password: '55555',
    rank: 'Cpt',
    firstName: 'Karla',
    middleName: 'Neal',
    lastName: 'Golden',
    organization: '93 AGOW',
    officeSymbol: 'G4G',
    dodId: '5501403174',
  },
  {
    email: 'tonia.figueroa@us.af.mil',
    password: '55555',
    rank: 'SSgt',
    firstName: 'Tonia',
    middleName: 'Medina',
    lastName: 'Figueroa',
    organization: '1 FW',
    officeSymbol: 'D2F',
    dodId: '7555182608',
  },
  {
    email: 'may.watts@us.af.mil',
    password: '55555',
    rank: 'LtCol',
    firstName: 'May',
    middleName: 'Hallie',
    lastName: 'Watts',
    organization: '701 MUNSS',
    officeSymbol: 'E5A',
    dodId: '0231466266',
  },
  {
    email: 'cindy.bartlett@us.af.mil',
    password: '55555',
    rank: 'CMSgt',
    firstName: 'Cindy',
    middleName: 'Janet',
    lastName: 'Bartlett',
    organization: '377 SFG',
    officeSymbol: 'B1F',
    dodId: '1112754248',
  },
  {
    email: 'ramsey.pitts@us.af.mil',
    password: '55555',
    rank: 'Col',
    firstName: 'Ramsey',
    middleName: 'Abby',
    lastName: 'Pitts',
    organization: '1 FW',
    officeSymbol: 'A9E',
    dodId: '4268744057',
  },
  {
    email: 'alexandra.rutledge@us.af.mil',
    password: '55555',
    rank: 'LtCol',
    firstName: 'Alexandra',
    middleName: 'Casey',
    lastName: 'Rutledge',
    organization: '93 AGOW',
    officeSymbol: 'F2B',
    dodId: '8022228372',
  },
  {
    email: 'kerri.norman@us.af.mil',
    password: '55555',
    rank: 'Col',
    firstName: 'Kerri',
    middleName: 'Richardson',
    lastName: 'Norman',
    organization: '93 AGOW',
    officeSymbol: 'B8F',
    dodId: '4452365501',
  },
  {
    email: 'henson.slater@us.af.mil',
    password: '55555',
    rank: '2Lt',
    firstName: 'Henson',
    middleName: 'Kimberley',
    lastName: 'Slater',
    organization: '93 AGOW',
    officeSymbol: 'C6B',
    dodId: '6750618755',
  },
  {
    email: 'little.hogan@us.af.mil',
    password: '55555',
    rank: '1Lt',
    firstName: 'Little',
    middleName: 'Best',
    lastName: 'Hogan',
    organization: '2 BW',
    officeSymbol: 'G5A',
    dodId: '4885172312',
  },
  {
    email: 'rae.fuller@us.af.mil',
    password: '55555',
    rank: 'TSgt',
    firstName: 'Rae',
    middleName: 'Nell',
    lastName: 'Fuller',
    organization: '93 AGOW',
    officeSymbol: 'D6F',
    dodId: '4722066638',
  },
  {
    email: 'rosemarie.meyer@us.af.mil',
    password: '55555',
    rank: 'SMSgt',
    firstName: 'Rosemarie',
    middleName: 'Gertrude',
    lastName: 'Meyer',
    organization: '93 AGOW',
    officeSymbol: 'C4D',
    dodId: '4735367307',
  },
  {
    email: 'ernestine.owens@us.af.mil',
    password: '55555',
    rank: 'A1C',
    firstName: 'Ernestine',
    middleName: 'Huber',
    lastName: 'Owens',
    organization: '1 FW',
    officeSymbol: 'B5A',
    dodId: '4820824284',
  },
  {
    email: 'anderson.chambers@us.af.mil',
    password: '55555',
    rank: '2Lt',
    firstName: 'Anderson',
    middleName: 'Hickman',
    lastName: 'Chambers',
    organization: '23 ABW',
    officeSymbol: 'B6G',
    dodId: '2518378037',
  },
  {
    email: 'drake.collier@us.af.mil',
    password: '55555',
    rank: 'MSgt',
    firstName: 'Drake',
    middleName: 'Dalton',
    lastName: 'Collier',
    organization: '2 BW',
    officeSymbol: 'D5F',
    dodId: '3882160224',
  },
  {
    email: 'diane.flynn@us.af.mil',
    password: '55555',
    rank: 'MSgt',
    firstName: 'Diane',
    middleName: 'Dale',
    lastName: 'Flynn',
    organization: '2 BW',
    officeSymbol: 'E1D',
    dodId: '5772051023',
  },
  {
    email: 'roslyn.cummings@us.af.mil',
    password: '55555',
    rank: 'MSgt',
    firstName: 'Roslyn',
    middleName: 'Tamara',
    lastName: 'Cummings',
    organization: '2 BW',
    officeSymbol: 'D9C',
    dodId: '8348724187',
  },
  {
    email: 'beard.perez@us.af.mil',
    password: '55555',
    rank: '1Lt',
    firstName: 'Beard',
    middleName: 'Rebekah',
    lastName: 'Perez',
    organization: '377 SFG',
    officeSymbol: 'C4E',
    dodId: '1183886404',
  },
  {
    email: 'henry.russo@us.af.mil',
    password: '55555',
    rank: 'TSgt',
    firstName: 'Henry',
    middleName: 'Holloway',
    lastName: 'Russo',
    organization: '93 AGOW',
    officeSymbol: 'E3F',
    dodId: '4104623756',
  },
  {
    email: 'solomon.koch@us.af.mil',
    password: '55555',
    rank: '1Lt',
    firstName: 'Solomon',
    middleName: 'Montgomery',
    lastName: 'Koch',
    organization: '701 MUNSS',
    officeSymbol: 'C8B',
    dodId: '1406538258',
  },
  {
    email: 'imogene.garner@us.af.mil',
    password: '55555',
    rank: 'MSgt',
    firstName: 'Imogene',
    middleName: 'Barnett',
    lastName: 'Garner',
    organization: '93 AGOW',
    officeSymbol: 'B8A',
    dodId: '3866384803',
  },
  {
    email: 'roberts.mendez@us.af.mil',
    password: '55555',
    rank: 'CMSgt',
    firstName: 'Roberts',
    middleName: 'Elvia',
    lastName: 'Mendez',
    organization: '1 FW',
    officeSymbol: 'D9E',
    dodId: '2727213200',
  },
  {
    email: 'saundra.oliver@us.af.mil',
    password: '55555',
    rank: 'SSgt',
    firstName: 'Saundra',
    middleName: 'Blair',
    lastName: 'Oliver',
    organization: '93 AGOW',
    officeSymbol: 'F5A',
    dodId: '3701670802',
  },
  {
    email: 'beth.burris@us.af.mil',
    password: '55555',
    rank: '1Lt',
    firstName: 'Beth',
    middleName: 'Benjamin',
    lastName: 'Burris',
    organization: '93 AGOW',
    officeSymbol: 'F8C',
    dodId: '7712322673',
  },
  {
    email: 'rosales.parks@us.af.mil',
    password: '55555',
    rank: 'TSgt',
    firstName: 'Rosales',
    middleName: 'Hart',
    lastName: 'Parks',
    organization: '23 ABW',
    officeSymbol: 'E9G',
    dodId: '5711744570',
  },
  {
    email: 'velez.galloway@us.af.mil',
    password: '55555',
    rank: 'TSgt',
    firstName: 'Velez',
    middleName: 'Autumn',
    lastName: 'Galloway',
    organization: '377 SFG',
    officeSymbol: 'G2C',
    dodId: '8717757044',
  },
  {
    email: 'janna.ochoa@us.af.mil',
    password: '55555',
    rank: 'SSgt',
    firstName: 'Janna',
    middleName: 'Clemons',
    lastName: 'Ochoa',
    organization: '23 ABW',
    officeSymbol: 'A4D',
    dodId: '7660021862',
  },
  {
    email: 'hopper.barber@us.af.mil',
    password: '55555',
    rank: '1Lt',
    firstName: 'Hopper',
    middleName: 'Bullock',
    lastName: 'Barber',
    organization: '701 MUNSS',
    officeSymbol: 'F9A',
    dodId: '3870004835',
  },
  {
    email: 'jannie.merritt@us.af.mil',
    password: '55555',
    rank: 'SSgt',
    firstName: 'Jannie',
    middleName: 'Sykes',
    lastName: 'Merritt',
    organization: '93 AGOW',
    officeSymbol: 'G2G',
    dodId: '8367088173',
  },
  {
    email: 'dudley.ratliff@us.af.mil',
    password: '55555',
    rank: 'Cpt',
    firstName: 'Dudley',
    middleName: 'Campos',
    lastName: 'Ratliff',
    organization: '2 BW',
    officeSymbol: 'D4D',
    dodId: '7318151271',
  },
  {
    email: 'juana.payne@us.af.mil',
    password: '55555',
    rank: '1Lt',
    firstName: 'Juana',
    middleName: 'Chrystal',
    lastName: 'Payne',
    organization: '93 AGOW',
    officeSymbol: 'D2C',
    dodId: '1041617550',
  },
  {
    email: 'allyson.kaufman@us.af.mil',
    password: '55555',
    rank: 'TSgt',
    firstName: 'Allyson',
    middleName: 'Sutton',
    lastName: 'Kaufman',
    organization: '377 SFG',
    officeSymbol: 'F6G',
    dodId: '4065235436',
  },
  {
    email: 'jerry.stuart@us.af.mil',
    password: '55555',
    rank: 'CMSgt',
    firstName: 'Jerry',
    middleName: 'Ramos',
    lastName: 'Stuart',
    organization: '93 AGOW',
    officeSymbol: 'B6C',
    dodId: '8142068425',
  },
  {
    email: 'hunt.sweeney@us.af.mil',
    password: '55555',
    rank: 'Cpt',
    firstName: 'Hunt',
    middleName: 'Perry',
    lastName: 'Sweeney',
    organization: '23 ABW',
    officeSymbol: 'G7B',
    dodId: '3754743301',
  },
  {
    email: 'atkins.brock@us.af.mil',
    password: '55555',
    rank: 'SSgt',
    firstName: 'Atkins',
    middleName: 'Georgina',
    lastName: 'Brock',
    organization: '701 MUNSS',
    officeSymbol: 'D7F',
    dodId: '2225122465',
  },
  {
    email: 'margery.anthony@us.af.mil',
    password: '55555',
    rank: 'CMSgt',
    firstName: 'Margery',
    middleName: 'Bates',
    lastName: 'Anthony',
    organization: '701 MUNSS',
    officeSymbol: 'A1D',
    dodId: '2541072280',
  },
  {
    email: 'hunter.santana@us.af.mil',
    password: '55555',
    rank: '1Lt',
    firstName: 'Hunter',
    middleName: 'Melton',
    lastName: 'Santana',
    organization: '377 SFG',
    officeSymbol: 'E6B',
    dodId: '0327662567',
  },
  {
    email: 'elise.riley@us.af.mil',
    password: '55555',
    rank: 'Maj',
    firstName: 'Elise',
    middleName: 'Marquita',
    lastName: 'Riley',
    organization: '23 ABW',
    officeSymbol: 'C8C',
    dodId: '1051746641',
  },
  {
    email: 'bradford.alexander@us.af.mil',
    password: '55555',
    rank: 'MSgt',
    firstName: 'Bradford',
    middleName: 'Deanne',
    lastName: 'Alexander',
    organization: '2 BW',
    officeSymbol: 'E4F',
    dodId: '7435601522',
  },
  {
    email: 'francesca.haynes@us.af.mil',
    password: '55555',
    rank: 'MSgt',
    firstName: 'Francesca',
    middleName: 'Madden',
    lastName: 'Haynes',
    organization: '701 MUNSS',
    officeSymbol: 'G4A',
    dodId: '4060550648',
  },
  {
    email: 'sandra.bray@us.af.mil',
    password: '55555',
    rank: 'SSgt',
    firstName: 'Sandra',
    middleName: 'Cooke',
    lastName: 'Bray',
    organization: '2 BW',
    officeSymbol: 'E6A',
    dodId: '5531454215',
  },
  {
    email: 'hughes.holt@us.af.mil',
    password: '55555',
    rank: 'SrA',
    firstName: 'Hughes',
    middleName: 'Garner',
    lastName: 'Holt',
    organization: '140 MXG',
    officeSymbol: 'C2A',
    dodId: '6503178582',
  },
  {
    email: 'nichole.barr@us.af.mil',
    password: '55555',
    rank: 'SMSgt',
    firstName: 'Nichole',
    middleName: 'Mona',
    lastName: 'Barr',
    organization: '23 ABW',
    officeSymbol: 'C5A',
    dodId: '7783302862',
  },
  {
    email: 'pearl.wells@us.af.mil',
    password: '55555',
    rank: 'Maj',
    firstName: 'Pearl',
    middleName: 'Molly',
    lastName: 'Wells',
    organization: '1 FW',
    officeSymbol: 'B1C',
    dodId: '2068162856',
  },
  {
    email: 'hebert.ward@us.af.mil',
    password: '55555',
    rank: 'Maj',
    firstName: 'Hebert',
    middleName: 'Dena',
    lastName: 'Ward',
    organization: '377 SFG',
    officeSymbol: 'B8B',
    dodId: '3585117338',
  },
  {
    email: 'cathleen.juarez@us.af.mil',
    password: '55555',
    rank: 'LtCol',
    firstName: 'Cathleen',
    middleName: 'Clarissa',
    lastName: 'Juarez',
    organization: '140 MXG',
    officeSymbol: 'F5A',
    dodId: '0167458343',
  },
  {
    email: 'socorro.sargent@us.af.mil',
    password: '55555',
    rank: 'Maj',
    firstName: 'Socorro',
    middleName: 'Holden',
    lastName: 'Sargent',
    organization: '377 SFG',
    officeSymbol: 'A3D',
    dodId: '4737155128',
  },
  {
    email: 'hernandez.ray@us.af.mil',
    password: '55555',
    rank: '1Lt',
    firstName: 'Hernandez',
    middleName: 'Gonzales',
    lastName: 'Ray',
    organization: '140 MXG',
    officeSymbol: 'E5F',
    dodId: '4470640564',
  },
  {
    email: 'cummings.jimenez@us.af.mil',
    password: '55555',
    rank: 'TSgt',
    firstName: 'Cummings',
    middleName: 'Alexandria',
    lastName: 'Jimenez',
    organization: '93 AGOW',
    officeSymbol: 'D2E',
    dodId: '6240670175',
  },
  {
    email: 'violet.monroe@us.af.mil',
    password: '55555',
    rank: 'Amn',
    firstName: 'Violet',
    middleName: 'Caitlin',
    lastName: 'Monroe',
    organization: '93 AGOW',
    officeSymbol: 'C9F',
    dodId: '6736634783',
  },
]
