export const airmen = [
  {
    email: 'leonard.ayala@us.af.mil',
    rank: 'LtCol',
    firstName: 'Leonard',
    middleName: 'Vega',
    lastName: 'Ayala',
    organization: '1 FW',
    officeSymbol: 'MX1',
    dodId: '3147738647',
  },
  {
    email: 'avery.english@us.af.mil',
    rank: 'SSgt',
    firstName: 'Avery',
    middleName: 'Genevieve',
    lastName: 'English',
    organization: '2 BW',
    officeSymbol: 'MX1',
    dodId: '9604300221',
  },
  {
    email: 'buckley.petersen@us.af.mil',
    rank: '1Lt',
    firstName: 'Buckley',
    middleName: 'Preston',
    lastName: 'Petersen',
    organization: '93 AGOW',
    officeSymbol: 'MX4',
    dodId: '2174785148',
  },
  {
    email: 'minerva.malone@us.af.mil',
    rank: 'CMSgt',
    firstName: 'Minerva',
    middleName: 'Thornton',
    lastName: 'Malone',
    organization: '23 ABW',
    officeSymbol: 'S2',
    dodId: '5422884707',
  },
  {
    email: 'parker.bowen@us.af.mil',
    rank: 'CMSgt',
    firstName: 'Parker',
    middleName: 'Burks',
    lastName: 'Bowen',
    organization: '377 SFG',
    officeSymbol: 'A1',
    dodId: '8737747621',
  },
  {
    email: 'dorthy.glover@us.af.mil',
    rank: 'SrA',
    firstName: 'Dorthy',
    middleName: 'Mari',
    lastName: 'Glover',
    organization: '140 MXG',
    officeSymbol: 'S1',
    dodId: '3106708115',
  },
  {
    email: 'terrell.harper@us.af.mil',
    rank: 'LtCol',
    firstName: 'Terrell',
    middleName: 'Knapp',
    lastName: 'Harper',
    organization: '93 AGOW',
    officeSymbol: 'S5',
    dodId: '7652365372',
  },
  {
    email: 'buchanan.daniel@us.af.mil',
    rank: 'SMSgt',
    firstName: 'Buchanan',
    middleName: 'Inez',
    lastName: 'Daniel',
    organization: '23 ABW',
    officeSymbol: 'MX4',
    dodId: '6125464646',
  },
  {
    email: 'lynnette.harrison@us.af.mil',
    rank: '1Lt',
    firstName: 'Lynnette',
    middleName: 'Wyatt',
    lastName: 'Harrison',
    organization: '1 FW',
    officeSymbol: 'MX2',
    dodId: '7357028212',
  },
  {
    email: 'rachelle.valencia@us.af.mil',
    rank: 'CMSgt',
    firstName: 'Rachelle',
    middleName: 'Abby',
    lastName: 'Valencia',
    organization: '701 MUNSS',
    officeSymbol: 'S4',
    dodId: '4873785780',
  },
  {
    email: 'karin.bush@us.af.mil',
    rank: 'SMSgt',
    firstName: 'Karin',
    middleName: 'Herminia',
    lastName: 'Bush',
    organization: '93 AGOW',
    officeSymbol: 'S3',
    dodId: '7870086753',
  },
  {
    email: 'madge.trevino@us.af.mil',
    rank: 'CMSgt',
    firstName: 'Madge',
    middleName: 'Shelby',
    lastName: 'Trevino',
    organization: '701 MUNSS',
    officeSymbol: 'A4',
    dodId: '5384630615',
  },
  {
    email: 'horn.rice@us.af.mil',
    rank: 'SMSgt',
    firstName: 'Horn',
    middleName: 'Grant',
    lastName: 'Rice',
    organization: '701 MUNSS',
    officeSymbol: 'A1',
    dodId: '9080212433',
  },
  {
    email: 'carmen.chapman@us.af.mil',
    rank: 'Maj',
    firstName: 'Carmen',
    middleName: 'Maynard',
    lastName: 'Chapman',
    organization: '377 SFG',
    officeSymbol: 'A1',
    dodId: '8352731855',
  },
  {
    email: 'whitney.barr@us.af.mil',
    rank: 'LtCol',
    firstName: 'Whitney',
    middleName: 'Cortez',
    lastName: 'Barr',
    organization: '1 FW',
    officeSymbol: 'MX5',
    dodId: '6102434683',
  },
  {
    email: 'galloway.good@us.af.mil',
    rank: 'CMSgt',
    firstName: 'Galloway',
    middleName: 'Romero',
    lastName: 'Good',
    organization: '23 ABW',
    officeSymbol: 'S5',
    dodId: '9682481077',
  },
  {
    email: 'misty.webb@us.af.mil',
    rank: 'SSgt',
    firstName: 'Misty',
    middleName: 'Eunice',
    lastName: 'Webb',
    organization: '140 MXG',
    officeSymbol: 'A3',
    dodId: '2820121183',
  },
  {
    email: 'reva.riggs@us.af.mil',
    rank: 'Amn',
    firstName: 'Reva',
    middleName: 'Ramirez',
    lastName: 'Riggs',
    organization: '140 MXG',
    officeSymbol: 'MX3',
    dodId: '2443727340',
  },
  {
    email: 'green.smith@us.af.mil',
    rank: 'SSgt',
    firstName: 'Green',
    middleName: 'Vera',
    lastName: 'Smith',
    organization: '701 MUNSS',
    officeSymbol: 'S2',
    dodId: '3674216331',
  },
  {
    email: 'rowland.reese@us.af.mil',
    rank: '1Lt',
    firstName: 'Rowland',
    middleName: 'Jayne',
    lastName: 'Reese',
    organization: '377 SFG',
    officeSymbol: 'S1',
    dodId: '9374084613',
  },
  {
    email: 'montgomery.phillips@us.af.mil',
    rank: 'SMSgt',
    firstName: 'Montgomery',
    middleName: 'Lester',
    lastName: 'Phillips',
    organization: '93 AGOW',
    officeSymbol: 'S1',
    dodId: '3518547561',
  },
  {
    email: 'maryanne.mclean@us.af.mil',
    rank: 'Maj',
    firstName: 'Maryanne',
    middleName: 'Deborah',
    lastName: 'Mclean',
    organization: '1 FW',
    officeSymbol: 'S1',
    dodId: '7002803557',
  },
  {
    email: 'roy.frederick@us.af.mil',
    rank: 'SrA',
    firstName: 'Roy',
    middleName: 'Pollard',
    lastName: 'Frederick',
    organization: '23 ABW',
    officeSymbol: 'A2',
    dodId: '1653413860',
  },
  {
    email: 'harrison.dodson@us.af.mil',
    rank: 'Amn',
    firstName: 'Harrison',
    middleName: 'Lorena',
    lastName: 'Dodson',
    organization: '701 MUNSS',
    officeSymbol: 'A5',
    dodId: '1256038365',
  },
  {
    email: 'frances.macdonald@us.af.mil',
    rank: 'SSgt',
    firstName: 'Frances',
    middleName: 'Cross',
    lastName: 'Macdonald',
    organization: '2 BW',
    officeSymbol: 'A5',
    dodId: '3520703463',
  },
  {
    email: 'lana.fulton@us.af.mil',
    rank: 'MSgt',
    firstName: 'Lana',
    middleName: 'Small',
    lastName: 'Fulton',
    organization: '2 BW',
    officeSymbol: 'MX1',
    dodId: '4608565855',
  },
  {
    email: 'griffin.montgomery@us.af.mil',
    rank: 'SrA',
    firstName: 'Griffin',
    middleName: 'Darlene',
    lastName: 'Montgomery',
    organization: '93 AGOW',
    officeSymbol: 'S2',
    dodId: '7522614334',
  },
  {
    email: 'moss.garrison@us.af.mil',
    rank: '1Lt',
    firstName: 'Moss',
    middleName: 'Rachel',
    lastName: 'Garrison',
    organization: '2 BW',
    officeSymbol: 'A2',
    dodId: '6751588325',
  },
  {
    email: 'callie.robles@us.af.mil',
    rank: 'LtCol',
    firstName: 'Callie',
    middleName: 'Fox',
    lastName: 'Robles',
    organization: '2 BW',
    officeSymbol: 'A2',
    dodId: '9086364505',
  },
  {
    email: 'mable.mathis@us.af.mil',
    rank: 'Col',
    firstName: 'Mable',
    middleName: 'Debora',
    lastName: 'Mathis',
    organization: '2 BW',
    officeSymbol: 'S5',
    dodId: '7327571371',
  },
  {
    email: 'lourdes.winters@us.af.mil',
    rank: 'Amn',
    firstName: 'Lourdes',
    middleName: 'Lindsay',
    lastName: 'Winters',
    organization: '140 MXG',
    officeSymbol: 'MX1',
    dodId: '3475144108',
  },
  {
    email: 'ilene.pennington@us.af.mil',
    rank: 'MSgt',
    firstName: 'Ilene',
    middleName: 'Noreen',
    lastName: 'Pennington',
    organization: '701 MUNSS',
    officeSymbol: 'A5',
    dodId: '9807076565',
  },
  {
    email: 'colleen.wilkerson@us.af.mil',
    rank: 'A1C',
    firstName: 'Colleen',
    middleName: 'Finley',
    lastName: 'Wilkerson',
    organization: '701 MUNSS',
    officeSymbol: 'A2',
    dodId: '4484234702',
  },
  {
    email: 'foster.young@us.af.mil',
    rank: 'Cpt',
    firstName: 'Foster',
    middleName: 'Marcy',
    lastName: 'Young',
    organization: '2 BW',
    officeSymbol: 'MX2',
    dodId: '6614232775',
  },
  {
    email: 'hickman.stanley@us.af.mil',
    rank: 'SMSgt',
    firstName: 'Hickman',
    middleName: 'Gentry',
    lastName: 'Stanley',
    organization: '140 MXG',
    officeSymbol: 'S2',
    dodId: '1648870202',
  },
  {
    email: 'wilma.calhoun@us.af.mil',
    rank: 'SSgt',
    firstName: 'Wilma',
    middleName: 'Queen',
    lastName: 'Calhoun',
    organization: '2 BW',
    officeSymbol: 'S2',
    dodId: '6608515757',
  },
  {
    email: 'hewitt.henry@us.af.mil',
    rank: 'SrA',
    firstName: 'Hewitt',
    middleName: 'Roxie',
    lastName: 'Henry',
    organization: '1 FW',
    officeSymbol: 'A3',
    dodId: '8374545354',
  },
  {
    email: 'christa.newman@us.af.mil',
    rank: 'TSgt',
    firstName: 'Christa',
    middleName: 'Juanita',
    lastName: 'Newman',
    organization: '377 SFG',
    officeSymbol: 'MX5',
    dodId: '7335568874',
  },
  {
    email: 'castillo.armstrong@us.af.mil',
    rank: 'Maj',
    firstName: 'Castillo',
    middleName: 'Rosales',
    lastName: 'Armstrong',
    organization: '1 FW',
    officeSymbol: 'MX4',
    dodId: '3330775686',
  },
  {
    email: 'dionne.baker@us.af.mil',
    rank: 'SrA',
    firstName: 'Dionne',
    middleName: 'Sheena',
    lastName: 'Baker',
    organization: '140 MXG',
    officeSymbol: 'S4',
    dodId: '7826671410',
  },
  {
    email: 'betty.compton@us.af.mil',
    rank: 'Cpt',
    firstName: 'Betty',
    middleName: 'Janell',
    lastName: 'Compton',
    organization: '1 FW',
    officeSymbol: 'A3',
    dodId: '9647384455',
  },
  {
    email: 'marian.lowe@us.af.mil',
    rank: 'Col',
    firstName: 'Marian',
    middleName: 'Louella',
    lastName: 'Lowe',
    organization: '1 FW',
    officeSymbol: 'A1',
    dodId: '2160271727',
  },
  {
    email: 'beryl.berg@us.af.mil',
    rank: 'MSgt',
    firstName: 'Beryl',
    middleName: 'Gladys',
    lastName: 'Berg',
    organization: '93 AGOW',
    officeSymbol: 'S2',
    dodId: '6105846862',
  },
  {
    email: 'byers.decker@us.af.mil',
    rank: 'Amn',
    firstName: 'Byers',
    middleName: 'Kline',
    lastName: 'Decker',
    organization: '701 MUNSS',
    officeSymbol: 'S2',
    dodId: '6632666725',
  },
  {
    email: 'brandy.bray@us.af.mil',
    rank: 'TSgt',
    firstName: 'Brandy',
    middleName: 'Mullen',
    lastName: 'Bray',
    organization: '377 SFG',
    officeSymbol: 'A2',
    dodId: '9871765341',
  },
  {
    email: 'torres.mayer@us.af.mil',
    rank: '2Lt',
    firstName: 'Torres',
    middleName: 'Simpson',
    lastName: 'Mayer',
    organization: '701 MUNSS',
    officeSymbol: 'MX1',
    dodId: '8054541367',
  },
  {
    email: 'lidia.joyner@us.af.mil',
    rank: 'SSgt',
    firstName: 'Lidia',
    middleName: 'Obrien',
    lastName: 'Joyner',
    organization: '701 MUNSS',
    officeSymbol: 'S2',
    dodId: '5618132861',
  },
  {
    email: 'snyder.puckett@us.af.mil',
    rank: 'Col',
    firstName: 'Snyder',
    middleName: 'Brittney',
    lastName: 'Puckett',
    organization: '377 SFG',
    officeSymbol: 'A1',
    dodId: '3160381834',
  },
  {
    email: 'petersen.lawrence@us.af.mil',
    rank: 'SMSgt',
    firstName: 'Petersen',
    middleName: 'Hendrix',
    lastName: 'Lawrence',
    organization: '701 MUNSS',
    officeSymbol: 'A5',
    dodId: '7088885412',
  },
  {
    email: 'dena.garcia@us.af.mil',
    rank: 'MSgt',
    firstName: 'Dena',
    middleName: 'Franks',
    lastName: 'Garcia',
    organization: '377 SFG',
    officeSymbol: 'MX5',
    dodId: '5220732638',
  },
  {
    email: 'terra.neal@us.af.mil',
    rank: 'CMSgt',
    firstName: 'Terra',
    middleName: 'Maude',
    lastName: 'Neal',
    organization: '93 AGOW',
    officeSymbol: 'S5',
    dodId: '9147628555',
  },
  {
    email: 'hamilton.henson@us.af.mil',
    rank: 'SSgt',
    firstName: 'Hamilton',
    middleName: 'Janie',
    lastName: 'Henson',
    organization: '2 BW',
    officeSymbol: 'S4',
    dodId: '7321448838',
  },
  {
    email: 'lorie.graham@us.af.mil',
    rank: 'MSgt',
    firstName: 'Lorie',
    middleName: 'Moon',
    lastName: 'Graham',
    organization: '140 MXG',
    officeSymbol: 'S1',
    dodId: '9502527127',
  },
  {
    email: 'susanna.patel@us.af.mil',
    rank: 'MSgt',
    firstName: 'Susanna',
    middleName: 'Faith',
    lastName: 'Patel',
    organization: '23 ABW',
    officeSymbol: 'A4',
    dodId: '1457312511',
  },
  {
    email: 'adele.talley@us.af.mil',
    rank: 'Cpt',
    firstName: 'Adele',
    middleName: 'Mcneil',
    lastName: 'Talley',
    organization: '140 MXG',
    officeSymbol: 'S3',
    dodId: '8857211482',
  },
  {
    email: 'esmeralda.parrish@us.af.mil',
    rank: 'SrA',
    firstName: 'Esmeralda',
    middleName: 'Jody',
    lastName: 'Parrish',
    organization: '23 ABW',
    officeSymbol: 'S4',
    dodId: '8463004671',
  },
  {
    email: 'morrow.davenport@us.af.mil',
    rank: '1Lt',
    firstName: 'Morrow',
    middleName: 'Angelica',
    lastName: 'Davenport',
    organization: '93 AGOW',
    officeSymbol: 'A1',
    dodId: '5752555336',
  },
  {
    email: 'hart.melendez@us.af.mil',
    rank: 'A1C',
    firstName: 'Hart',
    middleName: 'Andrea',
    lastName: 'Melendez',
    organization: '377 SFG',
    officeSymbol: 'A1',
    dodId: '6753545053',
  },
  {
    email: 'webb.nielsen@us.af.mil',
    rank: '1Lt',
    firstName: 'Webb',
    middleName: 'Cathy',
    lastName: 'Nielsen',
    organization: '93 AGOW',
    officeSymbol: 'MX2',
    dodId: '9688524643',
  },
  {
    email: 'lucas.lewis@us.af.mil',
    rank: 'A1C',
    firstName: 'Lucas',
    middleName: 'Stefanie',
    lastName: 'Lewis',
    organization: '701 MUNSS',
    officeSymbol: 'S3',
    dodId: '3325535587',
  },
  {
    email: 'ida.bradshaw@us.af.mil',
    rank: 'Col',
    firstName: 'Ida',
    middleName: 'Wong',
    lastName: 'Bradshaw',
    organization: '2 BW',
    officeSymbol: 'MX2',
    dodId: '3782257745',
  },
  {
    email: 'roman.nixon@us.af.mil',
    rank: 'SMSgt',
    firstName: 'Roman',
    middleName: 'Watkins',
    lastName: 'Nixon',
    organization: '377 SFG',
    officeSymbol: 'S1',
    dodId: '6107572024',
  },
  {
    email: 'hodges.lee@us.af.mil',
    rank: 'Amn',
    firstName: 'Hodges',
    middleName: 'Clements',
    lastName: 'Lee',
    organization: '1 FW',
    officeSymbol: 'S1',
    dodId: '5677820308',
  },
  {
    email: 'elinor.marquez@us.af.mil',
    rank: 'Amn',
    firstName: 'Elinor',
    middleName: 'Adriana',
    lastName: 'Marquez',
    organization: '93 AGOW',
    officeSymbol: 'S2',
    dodId: '4063080240',
  },
  {
    email: 'blankenship.klein@us.af.mil',
    rank: 'LtCol',
    firstName: 'Blankenship',
    middleName: 'Gale',
    lastName: 'Klein',
    organization: '701 MUNSS',
    officeSymbol: 'A5',
    dodId: '8808855818',
  },
  {
    email: 'marva.prince@us.af.mil',
    rank: '1Lt',
    firstName: 'Marva',
    middleName: 'Norton',
    lastName: 'Prince',
    organization: '93 AGOW',
    officeSymbol: 'S1',
    dodId: '9107032735',
  },
  {
    email: 'cardenas.berry@us.af.mil',
    rank: '1Lt',
    firstName: 'Cardenas',
    middleName: 'Clemons',
    lastName: 'Berry',
    organization: '377 SFG',
    officeSymbol: 'S2',
    dodId: '2686415832',
  },
  {
    email: 'mullins.watts@us.af.mil',
    rank: 'SrA',
    firstName: 'Mullins',
    middleName: 'Kramer',
    lastName: 'Watts',
    organization: '2 BW',
    officeSymbol: 'MX4',
    dodId: '5855562003',
  },
  {
    email: 'jennings.deleon@us.af.mil',
    rank: '2Lt',
    firstName: 'Jennings',
    middleName: 'Garrett',
    lastName: 'Deleon',
    organization: '701 MUNSS',
    officeSymbol: 'A2',
    dodId: '3266042675',
  },
  {
    email: 'jimmie.summers@us.af.mil',
    rank: 'MSgt',
    firstName: 'Jimmie',
    middleName: 'Jaime',
    lastName: 'Summers',
    organization: '93 AGOW',
    officeSymbol: 'A1',
    dodId: '5527340310',
  },
  {
    email: 'julie.pittman@us.af.mil',
    rank: 'SSgt',
    firstName: 'Julie',
    middleName: 'Mccormick',
    lastName: 'Pittman',
    organization: '93 AGOW',
    officeSymbol: 'MX5',
    dodId: '9755550236',
  },
  {
    email: 'sampson.parsons@us.af.mil',
    rank: '2Lt',
    firstName: 'Sampson',
    middleName: 'Jenifer',
    lastName: 'Parsons',
    organization: '140 MXG',
    officeSymbol: 'S3',
    dodId: '7433623546',
  },
  {
    email: 'copeland.wright@us.af.mil',
    rank: 'SrA',
    firstName: 'Copeland',
    middleName: 'Nadia',
    lastName: 'Wright',
    organization: '2 BW',
    officeSymbol: 'MX2',
    dodId: '1271456216',
  },
  {
    email: 'underwood.west@us.af.mil',
    rank: 'A1C',
    firstName: 'Underwood',
    middleName: 'Corina',
    lastName: 'West',
    organization: '701 MUNSS',
    officeSymbol: 'S3',
    dodId: '9312365145',
  },
  {
    email: 'dorothy.stuart@us.af.mil',
    rank: '2Lt',
    firstName: 'Dorothy',
    middleName: 'Dora',
    lastName: 'Stuart',
    organization: '93 AGOW',
    officeSymbol: 'MX5',
    dodId: '2427757771',
  },
  {
    email: 'liza.bryant@us.af.mil',
    rank: 'SrA',
    firstName: 'Liza',
    middleName: 'Katherine',
    lastName: 'Bryant',
    organization: '23 ABW',
    officeSymbol: 'MX5',
    dodId: '6620625864',
  },
  {
    email: 'marta.patrick@us.af.mil',
    rank: 'TSgt',
    firstName: 'Marta',
    middleName: 'Dillon',
    lastName: 'Patrick',
    organization: '377 SFG',
    officeSymbol: 'S5',
    dodId: '8212670000',
  },
  {
    email: 'harrell.blair@us.af.mil',
    rank: 'Maj',
    firstName: 'Harrell',
    middleName: 'Ana',
    lastName: 'Blair',
    organization: '140 MXG',
    officeSymbol: 'S3',
    dodId: '6831071804',
  },
  {
    email: 'patton.collier@us.af.mil',
    rank: 'Col',
    firstName: 'Patton',
    middleName: 'Ericka',
    lastName: 'Collier',
    organization: '1 FW',
    officeSymbol: 'A1',
    dodId: '8854628103',
  },
  {
    email: 'kirsten.horne@us.af.mil',
    rank: 'TSgt',
    firstName: 'Kirsten',
    middleName: 'Morales',
    lastName: 'Horne',
    organization: '23 ABW',
    officeSymbol: 'MX4',
    dodId: '3318033715',
  },
  {
    email: 'kane.meyers@us.af.mil',
    rank: 'Cpt',
    firstName: 'Kane',
    middleName: 'Jaclyn',
    lastName: 'Meyers',
    organization: '93 AGOW',
    officeSymbol: 'S3',
    dodId: '6104402558',
  },
  {
    email: 'delaney.herrera@us.af.mil',
    rank: 'LtCol',
    firstName: 'Delaney',
    middleName: 'Lakisha',
    lastName: 'Herrera',
    organization: '23 ABW',
    officeSymbol: 'MX3',
    dodId: '9357213228',
  },
  {
    email: 'ollie.patton@us.af.mil',
    rank: 'SMSgt',
    firstName: 'Ollie',
    middleName: 'Diaz',
    lastName: 'Patton',
    organization: '377 SFG',
    officeSymbol: 'MX1',
    dodId: '5727154747',
  },
  {
    email: 'willis.wooten@us.af.mil',
    rank: 'Col',
    firstName: 'Willis',
    middleName: 'Cameron',
    lastName: 'Wooten',
    organization: '1 FW',
    officeSymbol: 'MX5',
    dodId: '1862834634',
  },
  {
    email: 'suzette.mcbride@us.af.mil',
    rank: 'MSgt',
    firstName: 'Suzette',
    middleName: 'Donna',
    lastName: 'Mcbride',
    organization: '2 BW',
    officeSymbol: 'A3',
    dodId: '7612313431',
  },
  {
    email: 'hendricks.sawyer@us.af.mil',
    rank: 'SrA',
    firstName: 'Hendricks',
    middleName: 'Peters',
    lastName: 'Sawyer',
    organization: '701 MUNSS',
    officeSymbol: 'MX5',
    dodId: '6822705681',
  },
  {
    email: 'jocelyn.snider@us.af.mil',
    rank: 'Col',
    firstName: 'Jocelyn',
    middleName: 'Houston',
    lastName: 'Snider',
    organization: '23 ABW',
    officeSymbol: 'MX1',
    dodId: '3547332553',
  },
  {
    email: 'courtney.taylor@us.af.mil',
    rank: 'MSgt',
    firstName: 'Courtney',
    middleName: 'Leslie',
    lastName: 'Taylor',
    organization: '140 MXG',
    officeSymbol: 'A4',
    dodId: '6166164281',
  },
  {
    email: 'selena.richmond@us.af.mil',
    rank: 'SrA',
    firstName: 'Selena',
    middleName: 'Wendi',
    lastName: 'Richmond',
    organization: '377 SFG',
    officeSymbol: 'MX2',
    dodId: '9317557516',
  },
  {
    email: 'howell.cote@us.af.mil',
    rank: 'LtCol',
    firstName: 'Howell',
    middleName: 'Middleton',
    lastName: 'Cote',
    organization: '2 BW',
    officeSymbol: 'A5',
    dodId: '5227417560',
  },
  {
    email: 'ila.jefferson@us.af.mil',
    rank: 'Maj',
    firstName: 'Ila',
    middleName: 'Alexis',
    lastName: 'Jefferson',
    organization: '23 ABW',
    officeSymbol: 'A1',
    dodId: '1718277613',
  },
  {
    email: 'leblanc.perry@us.af.mil',
    rank: 'Maj',
    firstName: 'Leblanc',
    middleName: 'Little',
    lastName: 'Perry',
    organization: '1 FW',
    officeSymbol: 'A1',
    dodId: '6170461524',
  },
  {
    email: 'jami.foley@us.af.mil',
    rank: 'MSgt',
    firstName: 'Jami',
    middleName: 'Clarissa',
    lastName: 'Foley',
    organization: '23 ABW',
    officeSymbol: 'MX5',
    dodId: '4757653241',
  },
  {
    email: 'lancaster.nelson@us.af.mil',
    rank: 'Maj',
    firstName: 'Lancaster',
    middleName: 'Selma',
    lastName: 'Nelson',
    organization: '701 MUNSS',
    officeSymbol: 'A2',
    dodId: '5162774500',
  },
  {
    email: 'autumn.mccarty@us.af.mil',
    rank: '1Lt',
    firstName: 'Autumn',
    middleName: 'Cleveland',
    lastName: 'Mccarty',
    organization: '2 BW',
    officeSymbol: 'S5',
    dodId: '1341520803',
  },
  {
    email: 'melody.gardner@us.af.mil',
    rank: 'TSgt',
    firstName: 'Melody',
    middleName: 'Arline',
    lastName: 'Gardner',
    organization: '1 FW',
    officeSymbol: 'S5',
    dodId: '5522723613',
  },
  {
    email: 'fisher.simmons@us.af.mil',
    rank: 'Cpt',
    firstName: 'Fisher',
    middleName: 'Alyce',
    lastName: 'Simmons',
    organization: '377 SFG',
    officeSymbol: 'S2',
    dodId: '9653567505',
  },
  {
    email: 'stuart.simon@us.af.mil',
    rank: 'Col',
    firstName: 'Stuart',
    middleName: 'Bowen',
    lastName: 'Simon',
    organization: '93 AGOW',
    officeSymbol: 'A5',
    dodId: '7403326661',
  },
  {
    email: 'merritt.baldwin@us.af.mil',
    rank: '1Lt',
    firstName: 'Merritt',
    middleName: 'Lilian',
    lastName: 'Baldwin',
    organization: '701 MUNSS',
    officeSymbol: 'MX3',
    dodId: '6437333204',
  },
  {
    email: 'gena.carpenter@us.af.mil',
    rank: 'MSgt',
    firstName: 'Gena',
    middleName: 'Pansy',
    lastName: 'Carpenter',
    organization: '377 SFG',
    officeSymbol: 'S1',
    dodId: '4231730634',
  },
]
