import { hashPassword } from '@redwoodjs/api'

const password = '123'
const [hashedPassword, salt] = hashPassword(password)

export const monitors = [
  {
    email: "dustin.iverson.1@us.af.mil",
    hashedPassword,
    salt,
    rank: 'SSgt',
    firstName: 'Dustin',
    middleName: 'William',
    lastName: 'Iverson',
    organization: '2 AMXS',
    officeSymbol: 'A1A',
    dodId: '2758016437',
    afsc: '2A551',
    roles: 'Monitor'
    },
    {
      email: "nick.sibus.1@us.af.mil",
      hashedPassword,
      salt,
      rank: 'SSgt',
      firstName: 'Nicholas',
      middleName: 'Nick',
      lastName: 'Sibus',
      organization: '2 AMXS',
      officeSymbol: 'A1A',
      dodId: '8016437104',
      afsc: '2A551',
      roles: 'Monitor'
    },
    {
      email: "john.noah.1@us.af.mil",
      hashedPassword,
      salt,
      rank: 'SSgt',
      firstName: 'John',
      middleName: 'Joseph',
      lastName: 'Noah',
      organization: '8 FS',
      officeSymbol: 'F1A',
      dodId: '4371042341',
      afsc: '2A951',
      roles: 'Monitor'
    },
    {
      email: "cody.carrell.1@us.af.mil",
      hashedPassword,
      salt,
      rank: 'SSgt',
      firstName: 'Cody',
      middleName: 'Wade',
      lastName: 'Carrell',
      organization: '8 FS',
      officeSymbol: 'F1A',
      dodId: '4323418897',
      afsc: '2A951',
      roles: 'Monitor'
    },
    {
      email: "billy.bob.1@us.af.mil",
      hashedPassword,
      salt,
      rank: 'SSgt',
      firstName: 'BillyBob',
      middleName: 'Bobby',
      lastName: 'JimBob',
      organization: '67 SOS',
      officeSymbol: 'S1A',
      dodId: '0987789054',
      afsc: '3P0X1',
      roles: 'Monitor'
    },
    {
      email: "ernest.foster.1@us.af.mil",
      hashedPassword,
      salt,
      rank: 'SSgt',
      firstName: 'Ernest',
      middleName: 'NMN',
      lastName: 'Foster',
      organization: '67 SOS',
      officeSymbol: 'S1A',
      dodId: '0911119054',
      afsc: '3P0X1',
      roles: 'Monitor'
    },
    {
      email: "kayla.smith.1@us.af.mil",
      hashedPassword,
      salt,
      rank: 'SSgt',
      firstName: 'Kayla',
      middleName: 'Marie',
      lastName: 'Smith',
      organization: '96 BS',
      officeSymbol: 'S1A',
      dodId: '2105632793',
      afsc: '1T0X1',
      roles: 'Monitor'
    },
    {
      email: "natalie.davis.1@us.af.mil",
      hashedPassword,
      salt,
      rank: 'SSgt',
      firstName: 'Natalie',
      middleName: 'May',
      lastName: 'Davis',
      organization: '96 BS',
      officeSymbol: 'S1A',
      dodId: '2107220810',
      afsc: '1T0X1',
      roles: 'Monitor'
    },
    {
      email: "emilia.willis.1@us.af.mil",
      hashedPassword,
      salt,
      rank: 'SSgt',
      firstName: 'Emilia',
      middleName: 'Kay',
      lastName: 'Willis',
      organization: '343 BS',
      officeSymbol: 'B1A',
      dodId: '3344550876',
      afsc: '3P0X1',
      roles: 'Monitor'
    },
    {
      email: "goku.son.1@us.af.mil",
      hashedPassword,
      salt,
      rank: 'SSgt',
      firstName: 'Goku',
      middleName: 'Kakarot',
      lastName: 'Son',
      organization: '343 BS',
      officeSymbol: 'B1A',
      dodId: '3256841001',
      afsc: '3P0X1',
      roles: 'Monitor'
    },
    {
      email: "andrew.jackson.1@us.af.mil",
      hashedPassword,
      salt,
      rank: 'SSgt',
      firstName: 'Andrew',
      middleName: 'NMN',
      lastName: 'Jackson',
      organization: '377 SFS',
      officeSymbol: 'S1A',
      dodId: '4329817288',
      afsc: '4Y0X1',
      roles: 'Monitor'
    },
    {
      email: "george.washington.1@us.af.mil",
      hashedPassword,
      salt,
      rank: 'SSgt',
      firstName: 'George',
      middleName: 'NMN',
      lastName: 'Washington',
      organization: '377 SFS',
      officeSymbol: 'S1A',
      dodId: '6608213321',
      afsc: '4Y0X1',
      roles: 'Monitor'
    },
    {
      email: "chris.stephens.1@us.af.mil",
      hashedPassword,
      salt,
      rank: 'SSgt',
      firstName: 'Chris',
      middleName: 'Jim',
      lastName: 'Stephens',
      organization: '701 MUNS',
      officeSymbol: 'M1A',
      dodId: '9871235208',
      afsc: '5J0X1',
      roles: 'Monitor'
    },
    {
      email: "joey.reynolds.1@us.af.mil",
      hashedPassword,
      salt,
      rank: 'SSgt',
      firstName: 'Joey',
      middleName: 'Michael',
      lastName: 'Reynolds',
      organization: '701 MUNS',
      officeSymbol: 'M1A',
      dodId: '8734610001',
      afsc: '5J0X1',
      roles: 'Monitor'
    },
]
